{
 "title": "ICAP Live Performance Dashboard",
 "tags": [ "templated" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "25s",
 "panels": [
  {
   "title": "Number of Users & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Users",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "startedT" ], "type": "field" },
       { "params": [ " /*3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "application name" }
     ]
    },
    {
     "alias": "Number of  Errors",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "application name" }
     ]
    }
   ]
  },
  {
   "title": "ICAP Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICAP-Check-Resource-Status",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Check-Resource-Status" }
     ]
    },
    {
     "alias": "ICAP-Check-Server-Status",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Check-Server-Status" }
     ]
    },
    {
     "alias": "ICAP-Document-Process",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Successes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Successes",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Errors",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Requests",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "ICAP Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICAP-Document-Download",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" }
     ]
    }
   ]
  },
  {
   "title": "ICAP Throughput",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "ICAP-Document-Process",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" }
     ]
    }
   ]
  },
  {
   "title": "ICAP Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICAP-Check-Resource-Status",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Check-Resource-Status" }
     ]
    },
    {
     "alias": "ICAP-Check-Server-Status",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Check-Server-Status" }
     ]
    },
    {
     "alias": "ICAP-Document-Process",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ICAP-Document-Upload" }
     ]
    }
   ]
  },
  {
   "title": "Running Server Statistics: Servers",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Number of Children",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Children_number" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Used Servers",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Used_Servers" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Free Servers",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Free_Servers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Server Statistics: Processes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Started Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Started_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Closed Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Closed_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Closing Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Closing_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Crashed Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Crashed_Processes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Req Mods",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_REQMODS" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Resp Mods",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_RESPMODS" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprocessed",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_UNPROCESSED" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprocessable",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_UNPROCESSABLE"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Requests Rebuilt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Requests Scanned",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REQUESTS_SCANNED"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Rebuild Failures",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REBUILD_FAILURES"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Rebuild Errors",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REBUILD_ERRORS"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Scans Rebuilt",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_SCAN_REBUILT"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Bytes In/Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Bytes In",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_BYTES_IN" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Bytes Out",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_BYTES_OUT" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: HTTP Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "HTTP Bytes In",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_HTTP_BYTES_IN"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "HTTP Bytes Out",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_HTTP_BYTES_OUT"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Body Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Body Bytes In",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_IN"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Body Bytes Out",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_OUT"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Body Bytes Scanned",
     "measurement": "Service_gw_rebuild_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_SCANNED"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  }
 ]
}