{
 "title": "ICAP Live Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"background-color:green;\" style=\"text-align:left;\">The endpoint for this run is: \nicap-client.uksouth.cloudapp.azure.com. Total users are 100000. Duration of test is 2100 seconds  </p>    "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Users & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Users",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "startedT" ], "type": "field" },
       { "params": [ "*25" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "application name" }
     ]
    },
    {
     "alias": "Number of  Errors",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "application name" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Successes",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Successes",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Errors",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Total Process Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Process Requests",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/ICAP-Document-Process/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Total Requests",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/ICAP-Document-Process/" }
     ]
    }
   ]
  },
  {
   "title": "Success ICAP Document Process Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pdf-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "csv-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "dxf-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "dxf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "jpeg-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpeg_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "odp-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "odp_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "odt-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "odt_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pptx-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "rtf-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "rtf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xls-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xlsm-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xlsm_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xlsx-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xlsx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xml-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xml_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "ppt-ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Failed ICAP Document process Response Times (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pdf-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "csv-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "dxf-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "dxf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "gif-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "jpeg-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpeg_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "odp-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "odp_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "odt-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "odt_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "pptx-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "rtf-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "rtf_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xls-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xlsm-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xlsm_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xlsx-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xlsx_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xml-ICAP-Document-Process-Fail",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xml_ICAP-Document-Process" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "ICAP Throughput",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "ICAP-Document-Process",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Document-Process/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Success ICAP Requests over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICAP-Document-Process-Success",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/ICAP-Document-Process/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Running Server Statistics: Servers",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Number of Children",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Children_number" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Used Servers",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Used_Servers" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Free Servers",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Free_Servers" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICAP  process error codes ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ICAP-Document-Process- Error 403",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "403" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/Document-Process/" }
     ]
    },
    {
     "alias": "ICAP-Document-Process- Error 500",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "500" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/Document-Process/" }
     ]
    },
    {
     "alias": "ICAP-Document-Process- Error 204",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "204" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/Document-Process/" }
     ]
    },
    {
     "alias": "ICAP-Document-Process- Error 502",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "502" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/Document-Process/" }
     ]
    },
    {
     "alias": "ICAP-Document-Process- Error 522",
     "measurement": "jmetericap",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "522" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/Document-Process/" }
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Requests",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Req Mods",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_REQMODS" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Resp Mods",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_RESPMODS" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprocessed",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_UNPROCESSED" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprocessable",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_UNPROCESSABLE"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Server Statistics: Processes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Started Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Started_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Closed Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Closed_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Closing Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Closing_Processes" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Crashed Processes",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Crashed_Processes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Bytes In/Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Bytes In",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_BYTES_IN" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Bytes Out",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       { "params": [ "Service_gw_rebuild_BYTES_OUT" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: HTTP Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "HTTP Bytes In",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_HTTP_BYTES_IN"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "HTTP Bytes Out",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_HTTP_BYTES_OUT"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Body Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Body Bytes In",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_IN"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Body Bytes Out",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_OUT"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Body Bytes Scanned",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_BODY_BYTES_SCANNED"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service gw_rebuild Statistics: Requests Rebuilt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Requests Scanned",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REQUESTS_SCANNED"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Rebuild Failures",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REBUILD_FAILURES"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Rebuild Errors",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_REBUILD_ERRORS"
        ],
        "type": "field"
       }
      ]
     ]
    },
    {
     "alias": "Scans Rebuilt",
     "measurement": "Running_Servers_Statistics",
     "select": [
      [
       {
        "params": [
         "Service_gw_rebuild_SCAN_REBUILT"
        ],
        "type": "field"
       }
      ]
     ]
    }
   ]
  }
 ]
}