{
 "title": "Demo-Dashboard SharePoint",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"background-color:green;\" style=\"text-align:left;\">The endpoint for this run is: \nsaaspoc1.sharepoint.com. Total users are 25. Duration of test is 900 seconds  </p>    "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users & Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Users",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "startedT" ], "type": "field" },
       { "params": [ "*1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Number of Errors",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Total Files Uploaded & Downloaded",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Uploaded_Files",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Upload_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Downloaded_Files",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Download_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Total_Files",
     "measurement": "jmetersharepoint",
     "query": "SELECT \"count\" FROM \"jmetersharepoint\" WHERE (\"transaction\" =~ /Download_File/ AND \"statut\" = 'ok' AND \"transaction\" =~ /Upload_File/) AND $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Fail Total Files Uploaded & Downloaded",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Uploaded_Files",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Upload_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Downloaded_Files",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Download_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "Total_Files",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Error Rate",
     "measurement": "sharepoint_statistics",
     "query": "SELECT sum(FailedRequests) * 100 / sum(TotalRequests) FROM \"sharepoint_statistics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "FailedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " * 100 /  sum(\"TotalRequests\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success File Upload Total per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "jpg_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pdf_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "png_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "ppt_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pptx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xls_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Success File Download Total per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "jpg_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pdf_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "png_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "ppt_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pptx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xls_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Success Upload File Response Time(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "jpg_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pdf_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "png_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "ppt_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pptx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xls_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Success Download File Response Time(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "jpg_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pdf_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "png_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "ppt_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "pptx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "xls_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Fail File Upload Total per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "gif_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "jpg_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "pdf_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "png_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "ppt_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "pptx_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xls_Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Upload_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Fail File Download Total per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "gif_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "jpg_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "jpg_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "pdf_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pdf_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "png_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "png_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "ppt_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "ppt_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "pptx_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "pptx_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "xls_Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "xls_Download_File" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Success Upload File Throughput(per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Upload_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Upload_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Success Download File Throughput (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Download_File",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/Download_File/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Error Types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Assertion Fail",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "/5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "Assertion failed" }
     ]
    },
    {
     "alias": "Error 500",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "500" }
     ]
    },
    {
     "alias": "Error 503",
     "measurement": "jmetersharepoint",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "503" }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"jmeter\"}"
    }
   ]
  }
 ]
}