{
 "title": "ProxySite-Live-Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"background-color:green;\" style=\"text-align:left;\">The proxy site url is is: \nassets.publishing.service.gov.uk.glasswall-icap.com. Total users are 20. Duration of test is 900 seconds  </p>    "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Users & Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Users",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "startedT" ], "type": "field" },
       { "params": [ "*1" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Number of Errors",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Types",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Assertion Fail",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "/5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "Assertion failed" }
     ]
    },
    {
     "alias": "Error 500",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "500" }
     ]
    },
    {
     "alias": "Error 503",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ " / 5" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "responseCode", "operator": "=", "value": "503" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Error Rate",
     "measurement": "proxy_statistics",
     "query": "SELECT sum(FailedRequests) * 100 / sum(TotalRequests) FROM \"proxy_statistics\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "FailedRequests" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " * 100 /  sum(\"TotalRequests\")"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success File Process Total per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Fail File Process Total Per Type",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Success File Process Response Time(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Fail File Process Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Success File Process Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "gif_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Fail File Process Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "csv_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "csv_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "doc_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "doc_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "docx_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "docx_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "gif_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "gif_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "html_FileProcess",
     "measurement": "jmeterproxysite",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "html_FileProcess" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  }
 ]
}