# This is a basic workflow to help you get started with Actions

name: packer_build
env:
  AWS_DEFAULT_REGION: eu-west-1
# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * */7'



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ami:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
    - uses: actions/checkout@v2

    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

    # build artifact
    - name: Setup Packer
      run: |
        curl -o packer.zip https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
        unzip packer.zip
        sudo mv packer /usr/local/bin
        
    - name: Build AMI/OVA
      run: |
        packer build jmeter-icap/deployment/packer/aws-ova.json
      
